haisen/urls.py
from django.urls import path

from . import views

app_name = 'haisen'

urlpatterns = [
    path('notes/', views.notes, name='notes'),
    path('haisen_create/', views.HaisenCreateView.as_view(), name='haisen_create'),
    path('haiku_create_done/', views.haiku_create_done, name='haiku_create_done'),
    path('create_done/', views.create_done, name='create_done'),
    path('finished_work/', views.form_post, name='finished_work'),
    path('registration/', views.registration, name='registration'),
    path('haisen_list/', views.haisen_list, name='haisen_list'),
    ]

haisen_pytorch/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('haisen/', include('haisen.urls')),
]

haisen/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime
from django.utils import timezone

# Create your models here.

class Haisen(models.Model):
   class Meta:
       #テーブル名
       db_table ="Haisen"
       verbose_name ="俳句と川柳"           #追加
       verbose_name_plural ="俳句と川柳"    #追加

   #カラムの定義
   name = models.CharField(verbose_name="作者名", max_length=255)
   haisen = models.CharField(verbose_name="俳句や川柳", max_length=255)
   time = models.DateTimeField(default=timezone.now)
   """
   def __str__(self):
       return self.memo
   """

haisen/forms.py
from django import forms
from .models import Haisen

class HaisenForm(forms.ModelForm):
   """
   新規データ登録画面用のフォーム定義
   """
   class Meta:
       model = Haisen
       fields =['haisen',]

haisen/views.py
from django.shortcuts import render, redirect, reverse
from . forms import HaisenForm  #forms.pyからhaisenFormをインポート
from django.urls import reverse_lazy
from django.utils import timezone
from django.template.context_processors import csrf

# Create your views here.
#ここから下を追加
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Haisen
from . import forms
import logging

logger = logging.getLogger('development')

#一覧表示用のDjango標準ビュー(ListView)を承継して一覧表示用のクラスを定義
class HaisenListView(ListView):
   #利用するモデルを指定
   model = Haisen
   def post(self, request, *args, **kwargs):
        if self.request.POST.get('kami5', None):
            logger.debug("self.request.POST.get() = " + self.request.POST.get('kami5', None))
        if self.request.POST.getlist('title', None):
            logger.debug("self.request.POST.getlist() = " + self.request.POST.getlist('kami5', None)[0])
        return self.get(request, *args, **kwargs)
   """
   #データを渡すテンプレートファイルを指定
   template_name = 'haisen/haisen_list.html'

   #家計簿テーブルの全データを取得するメソッドを定義
   def queryset(self):
       return Haisen.objects.all()
   """

class HaisenCreateView(CreateView):
    #利用するモデルを指定
    model = Haisen
    #利用するフォームクラス名を指定
    form_class = HaisenForm
    #テンプレートを設定
    #デフォルトでは「アプリ名/モデル名_form.html」が設定されている
    template_name = "haisen/haisen_form.html"
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('haisen:create_done')

class HaikuCreateView(CreateView):
    #利用するモデルを指定
    model = Haisen
    #利用するフォームクラス名を指定
    form_class = HaisenForm
    template_name = "haisen/haiku_form.html"
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('haisen:haiku_create_done')

from haiku_module import haiku_return
from senryu_module import senryu_return

def haiku_create_done(request):
    user_kami5 = request.POST['kami5']
    # naka7_listには、AIが予測する中七の候補が順番に入る
    naka7_list = haiku_return(user_kami5)
    pre1 = user_kami5 + str(' ') + naka7_list[0]
    pre2 = user_kami5 + str(' ') + naka7_list[1]
    pre3 = user_kami5 + str(' ') + naka7_list[2]
    #登録処理が正常終了した場合に呼ばれるテンプレートを指定
    return render(request, 'haisen/create_done.html', {'total1':pre1, 'total2':pre2, 'total3':pre3})

def create_done(request):
    user_kami5 = request.POST['kami5']
    # naka7_listには、AIが予測する中七の候補が順番に入る
    naka7_list = senryu_return(user_kami5)
    pre1 = user_kami5 + str(' ') + naka7_list[0]
    pre2 = user_kami5 + str(' ') + naka7_list[1]
    pre3 = user_kami5 + str(' ') + naka7_list[2]
    #登録処理が正常終了した場合に呼ばれるテンプレートを指定
    return render(request, 'haisen/create_done.html', {'total1':pre1, 'total2':pre2, 'total3':pre3})

def form_post(request):
    kami5_naka7_list = request.POST['haisen'].split()
    kami5, naka7 = kami5_naka7_list[0], kami5_naka7_list[1]
    shimo5 = request.POST['text1']
    work = kami5 + (' ') + naka7 + (' ') + shimo5
    context = {
        'kami5_naka7': request.POST['haisen'],
        'kami5': kami5,
        'naka7':naka7,
        'shimo5': shimo5,
        'work': work
        }
    
    return render(request, 'haisen/finished_work.html', context)

# Haisenモデルに登録後、redirectする関数
def registration(request):
    if request.method == "POST":
        haisen, name = request.POST['work'], request.POST['name']
        Haisen.objects.create(haisen=haisen, name=name)
    return redirect(reverse_lazy('haisen:haisen_list'))

# Haisenモデルをhaisen_list.htmlに渡す関数
def haisen_list(request):
    data = Haisen.objects.all()
    return render(request, 'haisen/haisen_list.html', {'data': data})

def notes(request):
    return render(request, 'haisen/notes.html')

haisen/templates/haisen/base.html
<!doctype html>
<html style="height: 100%;">
<head>
 <meta charset="utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {# Bootstrap4を使う #}
 <!-- linkタグでbootstrapのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
 <!-- linkタグでDataTableのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>
 <!-- タイトルの設定-->
<title>インタラクティブ五七五</title>
</head>
<body style="height: 100%; overflow-y: scroll;">
<!--　▼ ジャンボトロン　 -->
<div class="jumbotron text-center" style="background:url(../../static/haisen/japanese-style_00002.jpg); 
            background-size: cover; background-position: center; height: 100%;">
      <div class="h-100 justify-content-center align-items-center">
      <p><h1 style="color: #ffffff; opacity: 1.0; text-shadow:0 0 7px #0b0b0b;">インタラクティブ<br class="d-lg-none">五七五</h1></p>
      <p>
      {% block content %}
      <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->
      {% endblock %}
      </p>
      </div>
</div>

 <!-- bootstrapのjavascript読み込み-->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
 <!-- DataTablesのjavascript読み込み-->
 <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
 <!-- chart.jsの読み込み -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

</div>
</body>
</html>

haisen/templates/haisen/create_done.html
{% extends 'haisen/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
    <form action="{% url 'haisen:finished_work' %}" method="post">
     <!-- Example DataTables Card-->
     <div class="card mb-3">
      <!--
      <div class="card-header">
        <i class="fa fa-server"></i> <h3>中七選択と下五入力</h3></div>-->
       <div class="card-body">
        <p>
          <label>
          <input type="radio" name="haisen" value="{{total1}}" required>{{total1}}
          </label>
        </p>
        <p>
          <label>
          <input type="radio" name="haisen" value="{{total2}}">{{total2}}
          </label>
        </p>
        <p>
          <label>
          <input type="radio" name="haisen" value="{{total3}}">{{total3}}
          </label>
        </p>
        <label for="text1">下五を入力する:</label>
        <input type="text" name="text1" class="form-control" required style="text-align: center;">
     </div>
     </div>
     </div>
     <!-- 遷移するボタン-->
     <p><button class="btn btn-success" type="submit" style="width:170px">五七五を完成させる</button></p>
      {% csrf_token %}
    <!-- formタグを閉じる -->
    </form>
     <p><a class="btn btn-dark" style="width:170px" 
      href="{% url 'haisen:haisen_create' %}" role="button">上五の入力に戻る</a></p>

{% endblock content %}

haisen/templates/haisen/finished_work.html
<!doctype html>
{% load static %}
<html style="height: 100%;">
<head>
 <meta charset="utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {# Bootstrap4を使う #}
 <!-- linkタグでbootstrapのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
 <!-- linkタグでDataTableのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>
 <link rel="stylesheet" href="{% static 'css/test.css' %}">
 <!-- タイトルの設定-->
<title>インタラクティブ五七五</title>
</head>
<body style="height: 100%; overflow-y: scroll;">

<!--　▼ ジャンボトロン　 -->
<div class="jumbotron" style="background:url({% static 'haisen/japanese-style_00002.jpg' %}); 
            background-size: cover; background-position: center; height: 100%;">

<form action="{% url 'haisen:registration' %}" method="post">
<div class="mx-auto" style="width: 200px;">
    <section class="ikku" style="writing-mode: vertical-rl;">
    <p>
        <font>{{kami5}}</font>
    </p>
    <p style="padding-top: 3em;">
        <font>{{naka7}}</font>
    </p>
    <p style="padding-top: 9em;">
        <font>{{shimo5}}</font>
    </p>
    </section>
    <label for="name" style="color:white; text-align:center; display: block;">ペンネームを入力する:</label>
    <input type="text" name="name" class="form-control" style="text-align: center;">
</div>
<div class="center" style="text-align:center;">
    <br>
    <button class="btn btn-success" type="submit" name="work" value="{{work}}" style="width:170px">作品を登録する</button>
    <a class="btn btn-dark" style="width:170px" 
        href="{% url 'haisen:haisen_create' %}" role="button">上五の入力に戻る</a>
</div>
{% csrf_token %}
<!-- formタグを閉じる -->
</form>

haisen/templates/haisen/haisen_form.html
{% extends 'haisen/base.html' %}
{% load bootstrap %}
{% block content %}

 <!-- formタグを設定し、postメソッドを指定 -->
 <form action="{% url 'haisen:haiku_create_done' %}" method="post">
   <div class="container">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">
             <!-- Example DataTables Card-->
             <div class="card mb-3">
               <div class="card-header">
                 <i class="fa fa-server"></i> <h4><b>上五の入力</b></h4></div>
               <div class="card-body";>          
                <label for="text1">五・七・五の上五を入力すると、<br class="d-lg-none">AIが中七の候補を返します。</label>
                <input type="text" name="kami5" class="form-control" required style="text-align: center;">
       </div>
     </div>
     <div class="row">
       <div class="col-12">
         <!-- データ保存ボタンを設定 -->
         <p><button class="btn btn-success" style="width:170px">俳句風の中七を生成</button></p>
         <p><button class="btn btn-success" type="submit" formaction="{% url 'haisen:create_done' %}" 
          style="width:170px">川柳風の中七を生成</button></p>
         <p><a class="btn btn-dark" style="width:170px" 
            href="{% url 'haisen:haisen_list' %}" role="button">作品リストを見る</a></p>
       </div>
     </div>
      <!-- <a href="{% url 'haisen:notes' %}">
       <b><font size="3" color="white">※アプリに関する注意点<br class="d-lg-none">（クリックしてご確認ください）</font></b>
      </a> -->
   </div>
   {% csrf_token %}
         <!-- formタグを閉じる -->
 </form>
{% endblock %}

haisen/templates/haisen/haisen_list.html
<!doctype html>
<html style="height: 100%;">
<head>
 <meta charset="utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {# Bootstrap4を使う #}
 <!-- linkタグでbootstrapのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
 <!-- linkタグでDataTableのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>
 <!-- タイトルの設定-->
<title>インタラクティブ五七五</title>
</head>
<body style="height: 100%; overflow-y: scroll;">

<!--　▼ ジャンボトロン　 -->
<div class="h-100 justify-content-center align-items-center" style="text-align: center;">
 <div class="content-wrapper">
   <div class="container-fluid">
     <!--ページタイトル-->
     <h1>作品リスト</h1>
     登録した作品を削除したい場合は、
     <br class="d-lg-none">
     <a href="https://docs.google.com/forms/d/e/1FAIpQLSeEk06-e8StuphJ4-wg7NrKDHYCKFBQk0or-8NVm7HyPLLqZQ/viewform">
      <b>こちらのフォームまで</b></a>お願いします。
     <div class="card mb-3">
       <div class="card-body">
         <!-- テーブル表の定義 -->
         <div class="table-responsive">
         <table id=haisen_list width="100%" class="table text-nowrap table-striped table-condensed table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">ペンネーム</th>
                 <th class="text-center">作品</th>
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in data %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="50">{{item.name}}</td>
                   <td class="text-center" width="100">{{item.haisen}}</td>
                 </tr>
               {% endfor %}
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
       </div>
      </div>
      </div>
      <p><a class="btn btn-dark" style="width:170px" 
        href="{% url 'haisen:haisen_create' %}" role="button">上五の入力に戻る</a></p>
   </div>
  </div>

 <!-- bootstrapのjavascript読み込み-->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
 <!-- DataTablesのjavascript読み込み-->
 <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
 <!-- chart.jsの読み込み -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<!-- Databableの定義-->
<script>
    jQuery(function($){
      // デフォルトの設定を変更
      $.extend( $.fn.dataTable.defaults, {
          language: {
              url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
              }
              });
      $("#haisen_list").DataTable({
          "searching": true,     //検索機能
          "paging":   true,      //ページング機能
          "ordering": true,      //ソート機能
          "lengthChange": true,  //件数切り替え機能

          }).columns.adjust().draw();
          });
</script>
</body>
</html>

haisen/templates/haisen/notes.html
<!doctype html>
<html style="height: 100%;">
<head>
 <meta charset="utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {# Bootstrap4を使う #}
 <!-- linkタグでbootstrapのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
 <!-- linkタグでDataTableのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>
 <!-- タイトルの設定-->
<title>インタラクティブ五七五</title>
</head>
<body style="height: 100%; overflow-y: scroll;">

<!--　▼ ジャンボトロン　 -->
 <div class="content-wrapper">
   <div class="container-fluid">
     <!--ページタイトル-->
<div class="container">
     <div class="row">
          <div class="col-md-6 col-md-offset-3">
               <h2 class="text-center">アプリに関する注意点</h2>
               この度は、インタラクティブ五七五をご使用いただき誠にありがとうございます。<br><br>
               このアプリには、五七五の作品を登録・閲覧する機能がございます。登録する際の注意点は下記の通りです。
               <br><br>
               <ol>
                    <li>作品およびペンネームは、不特定多数の人に閲覧される可能性があること</li>
                    <li>作品は、ペンネームを伏せた上で研究に用いる場合があること</li>
                    <li>作品は、予告なくアプリ上から削除される場合があること</li>
               </ol>
               以上の点についてご同意いただける場合は、是非作品を登録していただけますと幸いです。
          </div>
     </div>
<br>
<p class="text-center"><a class="btn btn-dark" style="width:170px" 
        href="{% url 'haisen:haisen_create' %}" role="button">上五の入力に戻る</a></p>
   </div>
  </div>

haisen/templates/haisen/senryu_form.html
{% extends 'haisen/base.html' %}
{% load bootstrap %}
{% block content %}

 <!-- formタグを設定し、postメソッドを指定 -->
 <form action="{% url 'haisen:create_done' %}" method="post">
   <div class="container">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">
             <!-- Example DataTables Card-->
             <div class="card mb-3">
               <div class="card-header">
                 <i class="fa fa-server"></i> <h3>上五入力（川柳風）</h3></div>
               <div class="card-body";>          
                <label for="text1">五・七・五の上五を入力すると、AIが中七の候補を返します。</label>
                <input type="text" name="kami5" class="form-control" required style="text-align: center;">
       </div>
     </div>
     <div class="row">
       <div class="col-12">
         <!-- データ保存ボタンを設定 -->
         <p><button class="btn btn-primary" style="width:150px">中七を生成する</button></p>
         <p><a class="btn btn-success" style="width:150px" href="{% url 'haisen:haiku_create' %}" role="button">俳句風に切り替える</a></p>
       </div>
     </div>
   </div>
   {% csrf_token %}
         <!-- formタグを閉じる -->
 </form>
{% endblock %}